### ISSUE TITLE
[REQUEST] Add locale/internationalization support

### ISSUE THREAD

**Issue by redtechtiger** [seanmorley15/AdventureLog#353] opened 2024-10-25 21:37 UTC
As the popularity of AdventureLog grows, it's becoming increasingly more important to provide a comfortable and intuitive user experience for users from different backgrounds. Many would appreciate languages other than English to be available for their travel logging needs, and there seems to be multiple users who would like to help with translation efforts.

There are multiple ways of implementing internationalization support; however, a quick search seems to indicate that [kaisermann/svelte-i18n](https://github.com/kaisermann/svelte-i18n) is a drop-in replacement that would satisfy our requirements. Also worth considering are the following tutorials and blog posts that touch on how this library would be used: [here](https://blog.logrocket.com/implementing-localization-svelte/), [here](https://phrase.com/blog/posts/a-step-by-step-guide-to-svelte-localization-with-svelte-i18n-v3/), [here](https://centus.com/blog/svelte-localization) and [here](https://lokalise.com/blog/svelte-i18n/).

This is something I would be happy to work on in the coming weeks after I've gotten my college applications done, so no rush if you have other features in the works.

**Comment by seanmorley15** [comment] 2024-10-29 14:34
Going to close this issue because it's a duplicate of #312. There is existing conversation on that thread. Thanks!

**Closed by seanmorley15** 2024-10-29 14:34 UTC
Labels: enhancement
